ALTER TABLE users
ADD COLUMN phone VARCHAR(20),
ADD COLUMN address VARCHAR(255),
ADD COLUMN city VARCHAR(100),
ADD COLUMN province VARCHAR(100),
ADD COLUMN postal_code VARCHAR(20),
ADD COLUMN payment_method VARCHAR(50),
ADD COLUMN card_number VARCHAR(20),
ADD COLUMN card_expiry VARCHAR(5),
ADD COLUMN card_cvv VARCHAR(3),
ADD COLUMN is_seller BOOLEAN DEFAULT FALSE;
